# FermiHDI Network Foundation Platform
# FermiHDI Limited
# No License
# Copyright (c) 2024

services:
  test_a:
    image: fermihdi:test-point
    build: ./test-points
    networks:
      a_load:
        ipv4_address: 10.140.110.100
    cap_add:
      - NET_ADMIN
    environment:
      LAB_ROUTE: "10.140.0.0/16"
      LAB_ROUTE_VIA: "10.140.110.2"
  test_b:
    image: fermihdi:test-point
    build: ./test-points
    networks:
      b_load:
        ipv4_address: 10.140.120.100
    cap_add:
      - NET_ADMIN
    environment:
      LAB_ROUTE: "10.140.0.0/16"
      LAB_ROUTE_VIA: "10.140.120.2"
  test_c1:
    image: fermihdi:test-point
    build: ./test-points
    networks:
      c_load1:
        ipv4_address: 10.140.130.100
    cap_add:
      - NET_ADMIN
    environment:
      LAB_ROUTE: "10.140.0.0/16"
      LAB_ROUTE_VIA: "10.140.130.2"
  test_c2:
    image: fermihdi:test-point
    build: ./test-points
    networks:
      c_load2:
        ipv4_address: 10.140.140.100
    cap_add:
      - NET_ADMIN
    environment:
      LAB_ROUTE: "10.140.0.0/16"
      LAB_ROUTE_VIA: "10.140.140.2"

networks:
  a_load:
    ipam:
      driver: default
      config:
        - subnet: 10.140.110.0/24
          gateway: 10.140.110.1
  b_load:
    ipam:
      driver: default
      config:
        - subnet: 10.140.120.0/24
          gateway: 10.140.120.1
  c_load1:
    ipam:
      driver: default
      config:
        - subnet: 10.140.130.0/24
          gateway: 10.140.130.1
  c_load2:
    ipam:
      driver: default
      config:
        - subnet: 10.140.140.0/24
          gateway: 10.140.140.1
