# FermiHDI Network Foundation Platform
# FermiHDI Limited
# No License
# Copyright (c) 2024

name: fermihdi-data-gen
services:
  router-a:
    image: frr:base
    build: ./router
    hostname: router-a
    container_name: router-a
    volumes:
      - ./router/config_files/router_a.conf:/etc/frr/frr.conf
      - ./router/config_files/daemons.conf:/etc/frr/daemons
      - ./router/config_files/pmacctd.conf:/etc/pmacct/pmacctd.conf
      - ./router/config_files/pmacctd.interfaces.map:/etc/pmacct/pmacctd.interfaces.map
      - ./router/config_files/docker-start.sh:/usr/lib/frr/docker-start
      - /lib/modules:/lib/modules
    init: false
    privileged: true
    networks:
      router-transit:
        ipv4_address: 10.140.0.100
      router-a-load:
        ipv4_address: 10.140.10.10
      router-a-services:
        ipv4_address: 10.142.10.10
      outside:
  router-b:
    image: frr:base
    build: ./router
    hostname: router-b
    container_name: router-b
    volumes:
      - ./router/config_files/router_b.conf:/etc/frr/frr.conf
      - ./router/config_files/daemons.conf:/etc/frr/daemons
      - ./router/config_files/pmacctd.conf:/etc/pmacct/pmacctd.conf
      - ./router/config_files/pmacctd.interfaces.map:/etc/pmacct/pmacctd.interfaces.map
      - ./router/config_files/docker-start.sh:/usr/lib/frr/docker-start
      - /lib/modules:/lib/modules
    init: false
    privileged: true
    networks:
      router-transit:
        ipv4_address: 10.140.0.101
      router-b-load:
        ipv4_address: 10.140.20.10
      router-b-services:
        ipv4_address: 10.140.30.10
      outside:
  load-master:
    image: locust
    build: ./load
    container_name: locust-master
    ports:
      - "9089:8089"
      - "5557:5557"
    volumes:
      - ./load/locust-master.conf:/usr/src/app/locust-master.conf
      - ./load/locustfile.py:/usr/src/app/locustfile.py
    command: --config /usr/src/app/locust-master.conf --host http://webapp:3000
    depends_on:
      - webapp
      - router-a
      - router-b
    networks:
      router-a-load:
      outside:
    extra_hosts:
      webapp: "10.140.20.3"
    cap_add:
      - NET_ADMIN
  load-worker:
    image: locust
    build: ./load
    deploy:
      replicas: 4
    volumes:
      - ./load/locust-worker.conf:/usr/src/app/locust-worker.conf
      - ./load/locustfile.py:/usr/src/app/locustfile.py
    command: --config /usr/src/app/locust-worker.conf --master-host load-master
    depends_on:
      - load-master
    networks:
      router-a-load:
      outside:
    cap_add:
      - NET_ADMIN
  webapp:
    image: webapp
    build: ./webapp
    container_name: webapp
    command: ["--", "--redis", "redis"]
    ports:
      - 3000:3000
    networks:
      outside:
      router-b-load:
        ipv4_address: 10.140.20.3
    extra_hosts:
      redis: "10.140.30.3"
    cap_add:
      - NET_ADMIN
    depends_on:
      - redis
  redis:
    image: redis
    build: ./redis
    container_name: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      router-b-services:
        ipv4_address: 10.140.30.3
    cap_add:
      - NET_ADMIN

networks:
  router-transit:
    ipam:
      driver: default
      config:
        - subnet: 10.140.0.0/24
          gateway: 10.140.0.1
  router-a-load:
    ipam:
      driver: default
      config:
        - subnet: 10.140.10.0/24
          gateway: 10.140.10.10
  router-a-services:
    ipam:
      driver: default
      config:
        - subnet: 10.142.10.0/24
          gateway: 10.142.10.10
  router-b-load:
    ipam:
      driver: default
      config:
        - subnet: 10.140.20.0/24
          gateway: 10.140.20.10
  router-b-services:
    ipam:
      driver: default
      config:
        - subnet: 10.140.30.0/24
          gateway: 10.140.30.10
  managment:
    external: true
  outside: {}
