# FermiHDI Network Foundation Platform
# FermiHDI Limited
# No License
# Copyright (c) 2024

name: fh_beta
services:
  router_a:
    image: fermihdi:lab-router
    build: .
    hostname: router-a
    volumes:
      - ./router-a.conf:/etc/frr/frr.conf
      - ./daemons.conf:/etc/frr/daemons
      - ./pmacctd.conf:/etc/pmacct/pmacctd.conf
      - ./pmacctd.interfaces.map:/etc/pmacct/pmacctd.interfaces.map
      - /lib/modules:/lib/modules
    init: false
    privileged: true
    networks:
      a_b_transit:
        ipv4_address: 10.140.0.2
      a_c_transit:
        ipv4_address: 10.140.10.2
      a_load:
        ipv4_address: 10.140.110.2
      telemetry:
  router_b:
    image: fermihdi:lab-router
    build: .
    hostname: router-b
    volumes:
      - ./router-b.conf:/etc/frr/frr.conf
      - ./daemons.conf:/etc/frr/daemons
      - ./pmacctd.conf:/etc/pmacct/pmacctd.conf
      - ./pmacctd.interfaces.map:/etc/pmacct/pmacctd.interfaces.map
      - /lib/modules:/lib/modules
    init: false
    privileged: true
    networks:
      a_b_transit:
        ipv4_address: 10.140.0.3
      b_load:
        ipv4_address: 10.140.120.2
      telemetry:
      outside:
  router_c:
    image: fermihdi:lab-router
    build: .
    hostname: router-c
    volumes:
      - ./router-c.conf:/etc/frr/frr.conf
      - ./daemons.conf:/etc/frr/daemons
      - ./pmacctd.conf:/etc/pmacct/pmacctd.conf
      - ./pmacctd.interfaces.map:/etc/pmacct/pmacctd.interfaces.map
      - /lib/modules:/lib/modules
    init: false
    privileged: true
    networks:
      a_c_transit:
        ipv4_address: 10.140.10.3
      c_load1:
        ipv4_address: 10.140.130.2
      c_load2:
        ipv4_address: 10.140.140.2
      telemetry:
      outside:
  test_a:
    image: fermihdi:test-point
    build: ./test-points
    networks:
      a_load:
        ipv4_address: 10.140.110.100
    cap_add:
      - NET_ADMIN
  test_b:
    image: fermihdi:test-point
    build: ./test-points
    networks:
      b_load:
        ipv4_address: 10.140.120.100
    cap_add:
      - NET_ADMIN
  test_c1:
    image: fermihdi:test-point
    build: ./test-points
    networks:
      c_load1:
        ipv4_address: 10.140.130.100
    cap_add:
      - NET_ADMIN
  test_c2:
    image: fermihdi:test-point
    build: ./test-points
    networks:
      c_load2:
        ipv4_address: 10.140.140.100
    cap_add:
      - NET_ADMIN

networks:
  a_b_transit:
    ipam:
      driver: default
      config:
        - subnet: 10.140.0.0/24
          gateway: 10.140.0.1
  a_c_transit:
    ipam:
      driver: default
      config:
        - subnet: 10.140.10.0/24
          gateway: 10.140.10.1
  a_load:
    ipam:
      driver: default
      config:
        - subnet: 10.140.110.0/24
          gateway: 10.140.110.1
  b_load:
    ipam:
      driver: default
      config:
        - subnet: 10.140.120.0/24
          gateway: 10.140.120.1
  c_load1:
    ipam:
      driver: default
      config:
        - subnet: 10.140.130.0/24
          gateway: 10.140.130.1
  c_load2:
    ipam:
      driver: default
      config:
        - subnet: 10.140.140.0/24
          gateway: 10.140.140.1
  telemetry:
    ipam:
      driver: default
      config:
        - subnet: 10.143.0.0/24
  kafka:
    ipam:
      driver: default
      config:
        - subnet: 10.145.0.0/24
  kafka-producers:
    ipam:
      driver: default
      config:
        - subnet: 10.145.10.0/24
  kafka-consumers:
    ipam:
      driver: default
      config:
        - subnet: 10.145.20.0/24
  outside: {}
